//
//  UIImage+effectWithCoreImage.h
//  coreImage_test
//
//  Created by ghostpf on 15/8/25.
//  Copyright (c) 2015年 ghostpf. All rights reserved.
//

#import <UIKit/UIKit.h>

@interface UIImage (effectWithCoreImage)

- (UIImage *)effectWithEffectName:(NSString *)name;

@end


//(
// CIAccordionFoldTransition,
// CIAdditionCompositing,
// CIAffineClamp,
// CIAffineTile,
// CIAffineTransform,
// CIAreaHistogram,
// CIAztecCodeGenerator,
// CIBarsSwipeTransition,
// CIBlendWithAlphaMask,
// CIBlendWithMask,
// CIBloom,
// CIBumpDistortion,
// CIBumpDistortionLinear,
// CICheckerboardGenerator,
// CICircleSplashDistortion,
// CICircularScreen,
// CICode128BarcodeGenerator,
// CIColorBlendMode,
// CIColorBurnBlendMode,
// CIColorClamp,
// CIColorControls,
// CIColorCrossPolynomial,
// CIColorCube,
// CIColorCubeWithColorSpace,
// CIColorDodgeBlendMode,
// CIColorInvert,
// CIColorMap,
// CIColorMatrix,
// CIColorMonochrome,
// CIColorPolynomial,
// CIColorPosterize,
// CIConstantColorGenerator,
// CIConvolution3X3,
// CIConvolution5X5,
// CIConvolution9Horizontal,
// CIConvolution9Vertical,
// CICopyMachineTransition,
// CICrop,
// CIDarkenBlendMode,
// CIDifferenceBlendMode,
// CIDisintegrateWithMaskTransition,
// CIDissolveTransition,
// CIDivideBlendMode,
// CIDotScreen,
// CIEightfoldReflectedTile,
// CIExclusionBlendMode,
// CIExposureAdjust,
// CIFalseColor,
// CIFlashTransition,
// CIFourfoldReflectedTile,
// CIFourfoldRotatedTile,
// CIFourfoldTranslatedTile,
// CIGammaAdjust,
// CIGaussianBlur,
// CIGaussianGradient,
// CIGlassDistortion,
// CIGlideReflectedTile,
// CIGloom,
// CIHardLightBlendMode,
// CIHatchedScreen,
// CIHighlightShadowAdjust,
// CIHistogramDisplayFilter,
// CIHoleDistortion,
// CIHueAdjust,
// CIHueBlendMode,
// CILanczosScaleTransform,
// CILightenBlendMode,
// CILightTunnel,
// CILinearBurnBlendMode,
// CILinearDodgeBlendMode,
// CILinearGradient,
// CILinearToSRGBToneCurve,
// CILineScreen,
// CILuminosityBlendMode,
// CIMaskToAlpha,
// CIMaximumComponent,
// CIMaximumCompositing,
// CIMinimumComponent,
// CIMinimumCompositing,
// CIModTransition,
// CIMotionBlur,
// CIMultiplyBlendMode,
// CIMultiplyCompositing,
// CIOverlayBlendMode,
// CIPerspectiveCorrection,

// CIPhotoEffectChrome,
// CIPhotoEffectFade,
// CIPhotoEffectInstant,
// CIPhotoEffectMono,
// CIPhotoEffectNoir,
// CIPhotoEffectProcess,
// CIPhotoEffectTonal,        黑白效果
// CIPhotoEffectTransfer,

// CIPinchDistortion,
// CIPinLightBlendMode,
// CIPixellate,               马赛克
// CIQRCodeGenerator,
// CIRadialGradient,
// CIRandomGenerator,
// CISaturationBlendMode,
// CIScreenBlendMode,
// CISepiaTone,
// CISharpenLuminance,
// CISixfoldReflectedTile,
// CISixfoldRotatedTile,
// CISmoothLinearGradient,
// CISoftLightBlendMode,
// CISourceAtopCompositing,
// CISourceInCompositing,
// CISourceOutCompositing,
// CISourceOverCompositing,
// CISRGBToneCurveToLinear,
// CIStarShineGenerator,
// CIStraightenFilter,
// CIStripesGenerator,
// CISubtractBlendMode,
// CISwipeTransition,
// CITemperatureAndTint,
// CIToneCurve,
// CITriangleKaleidoscope,
// CITwelvefoldReflectedTile,
// CITwirlDistortion,
// CIUnsharpMask,
// CIVibrance,
// CIVignette,
// CIVignetteEffect,
// CIVortexDistortion,
// CIWhitePointAdjust,
// CIZoomBlur
// ) 129个滤镜效果